from tkinter import *


def donothing():
    print("button selected")
    button = Button(text="do nothing")
    button.pack()
    
root = Tk()
root.title("*Untitled-Notepad")
root.wm_iconbitmap()
root.geometry("300x300")

# this is for text area
textarea = Text(root,font="Arial",undo=True)
file=None
textarea.pack(fill=BOTH,expand=True)



menubar = Menu(root)

filemenu = Menu(menubar,tearoff=0)
menubar.add_cascade(label="File",menu=filemenu)
filemenu.add_command(label = 'New Text File',accelerator="Ctrl+N", command= donothing)
filemenu.add_command(label = 'New File...',accelerator="Ctrl+Alt+Window+N",command= donothing)
filemenu.add_command(label = 'New Window',accelerator="Ctrl+Shift+N",command= donothing)
filemenu.add_separator()
filemenu.add_command(label = 'Open File...',accelerator="Ctrl+O", command= donothing)
filemenu.add_command(label = 'Open Folder...',accelerator="Ctrl+k+Ctrl+O", command= donothing)
filemenu.add_command(label='Open Worksapce from File... ',command=donothing)
filemenu.add_command(label='Open Recent',accelerator=">",command=donothing)
filemenu.add_separator()
filemenu.add_command(label = 'Add Folder to Workspace...', command= donothing)
filemenu.add_command(label = 'Save Workspace As...', command= donothing)
filemenu.add_command(label = 'Duplicate Workspace', command= donothing)
filemenu.add_separator()
filemenu.add_command(label = 'Save',accelerator="Ctrl+S", command= donothing)
filemenu.add_command(label = 'Save as...',accelerator="Ctrl+Shift+S", command= donothing)
filemenu.add_command(label = 'Save All',accelerator="Ctrl+K S", command= donothing)
filemenu.add_separator()
filemenu.add_command(label = 'Share',accelerator=">", command= donothing)
filemenu.add_separator()
filemenu.add_command(label = 'Auto Save',command= donothing)
filemenu.add_command(label = 'Preferences',accelerator=">",command= donothing)
filemenu.add_separator()
filemenu.add_command(label='Revert File',command=donothing)
filemenu.add_command(label='Close Editor',accelerator="Ctrl+F4",command=donothing)
filemenu.add_command(label='Close Folder',accelerator="Ctrl+K f",command=donothing)
filemenu.add_command(label='Close Window',accelerator="Ctrl+f4",command=donothing)
filemenu.add_separator()
filemenu.add_command(label='Exit',command=donothing)

editmenu = Menu(menubar,tearoff=0)
menubar.add_cascade(label="Edit",menu=editmenu)

editmenu.add_command(label = 'Undo',accelerator="ctrl+Z", command= donothing)
editmenu.add_command(label = 'Redo',accelerator="ctrl+Y", command= donothing)
editmenu.add_separator()
editmenu.add_command(label = 'Cut',accelerator="Ctrl+X", command= donothing)
editmenu.add_command(label = 'Copy',accelerator="Ctrl+C", command= donothing)
editmenu.add_command(label = 'paste', accelerator="Ctrl+V", command= donothing)
editmenu.add_separator()
editmenu.add_command(label = 'Find', accelerator="Ctrl+F", command= donothing)
editmenu.add_command(label = 'Replace', accelerator="Ctrl+H", command= donothing)
editmenu.add_separator()
editmenu.add_command(label = 'Find in Files', accelerator="Ctrl+Shift+F", command= donothing)
editmenu.add_command(label = 'Replace in Files', accelerator="Ctrl+Shift+H", command= donothing)
editmenu.add_separator()
editmenu.add_command(label = 'Toggle Line Comment', accelerator="Ctrl+/", command= donothing)
editmenu.add_command(label = 'Toggle Block Comment', accelerator="Shift+Alt+A ", command= donothing)
editmenu.add_command(label = 'Emmet: Expand Abbreviation', accelerator="Tab", command= donothing)

selectionmenu = Menu(menubar,tearoff = 0)
menubar.add_cascade(label="Selection",menu=selectionmenu)
selectionmenu.add_command(label = 'Select All',accelerator="Ctrl+A", command=donothing)
selectionmenu.add_command(label = 'Expand Selection',accelerator="Shift+Alt+RightArrow", command=donothing)
selectionmenu.add_command(label = 'Shrink Selection',accelerator="Shift+Alt+LeftArrow", command=donothing)
selectionmenu.add_separator()
selectionmenu.add_command(label = 'Copy Line Up',accelerator="Shift+Alt+UpArrow", command=donothing)
selectionmenu.add_command(label = 'Copy Line Down',accelerator="Shift+Alt+DownArrow", command=donothing)
selectionmenu.add_command(label = 'Move Line Up',accelerator="Alt+UpArrow",command=donothing)
selectionmenu.add_command(label = 'Move Line Down',accelerator="Alt+DownArrow",command=donothing)
selectionmenu.add_command(label = 'Duplicate Selection',command=donothing)
selectionmenu.add_separator()
selectionmenu.add_command(label = 'Add Cursor Above',accelerator="Ctrl+Alt+UpArrow",command=donothing)
selectionmenu.add_command(label = 'Add Cursor Below',accelerator="Ctrl+Alt+DownArrow",command=donothing)
selectionmenu.add_command(label = 'Add Cursor to Line Ends',accelerator="Shift+Alt=I",command=donothing)
selectionmenu.add_command(label = 'Add Next Occurence',accelerator="Ctrl+D",command=donothing)
selectionmenu.add_command(label = 'Add Previous Occurence',command=donothing)
selectionmenu.add_command(label = 'Select All Occurence',accelerator="Ctrl+Shift+L",command=donothing)
selectionmenu.add_command(label = 'Switch to Ctrl+Click for Multi-Cursor',command=donothing)
selectionmenu.add_command(label = 'Column Selection Mode',command=donothing)

viewmenu = Menu(menubar,tearoff=0)
menubar.add_cascade(label = "View", menu = viewmenu)

viewmenu.add_command(label = 'Command Palette',accelerator="Ctrl+Shift+P",command=donothing)
viewmenu.add_command(label = 'Open View...', command=donothing)
viewmenu.add_separator()
viewmenu.add_command(label = 'Appearance',accelerator=">",command=donothing)
viewmenu.add_command(label = 'Editor Layout',accelerator=">",command=donothing)
viewmenu.add_separator()
viewmenu.add_command(label = 'Explorer',accelerator="Ctrl+Shift+E",command=donothing)
viewmenu.add_command(label='Search',accelerator="Ctrl+Shift+F",command=donothing)
viewmenu.add_command(label='Source Control',accelerator="Ctrl+Shift+G",command=donothing)
viewmenu.add_command(label='Run',accelerator="Ctrl+Shift+D",command=donothing)
viewmenu.add_command(label='Extensions',accelerator="ewCtr+Shift+X",command=donothing)
viewmenu.add_command(label='Testing',command=donothing)
viewmenu.add_separator()
viewmenu.add_command(label='Problems',accelerator="Ctrl+Shift+M",command=donothing)
viewmenu.add_command(label='Output',accelerator="Ctrl+Shift+U",command=donothing)
viewmenu.add_command(label='Debug Console',accelerator="Ctrl+Shift+Y",command=donothing)
viewmenu.add_command(label='Terminal',accelerator="Ctrl+`",command=donothing)
viewmenu.add_separator()
viewmenu.add_command(label='Word Wrap',accelerator="Alt+Z",command=donothing)

gomenu = Menu(menubar,tearoff=0)
menubar.add_cascade(label="Go",menu=gomenu)

gomenu.add_command(label='Back',accelerator="Alt+LeftArrow",command=donothing)
gomenu.add_command(label='Forword',accelerator="Alt+RightArrow",command=donothing)
gomenu.add_command(label='Last Edit location',accelerator="Ctrl+k Ctrl+Q",command=donothing)
gomenu.add_separator()
gomenu.add_command(label='Switch Editor',accelerator=">",command=donothing)
gomenu.add_command(label='Switch Group',accelerator=">",command=donothing)
gomenu.add_separator()
gomenu.add_command(label='Go to File...',accelerator="Ctrl+P",command=donothing)
gomenu.add_command(label='Go to Symbol in Workspace...',accelerator="Ctrl+T",command=donothing)
gomenu.add_separator()
gomenu.add_command(label='Go to Symbol in Editor...',accelerator="Ctrl+Shift+O",command=donothing)
gomenu.add_command(label='Go to Definition',accelerator="F12",command=donothing)
gomenu.add_command(label='Go to Declaration',command=donothing)
gomenu.add_command(label='Go to Type Definition',command=donothing)
gomenu.add_command(label='Go to Implementations',accelerator="Ctrl+F12",command=donothing)
gomenu.add_command(label='Go to References',accelerator="Shift+F12",command=donothing)
gomenu.add_separator()
gomenu.add_command(label='Go to Line/Column...',accelerator="Ctrl+G",command=donothing)
gomenu.add_command(label='Go to Bracket',accelerator="Ctrl+Shift",command=donothing)
gomenu.add_separator()
gomenu.add_command(label='Next Problem',accelerator="F8",command=donothing)
gomenu.add_command(label='Previous Problem',accelerator="Shift+F8",command=donothing)

root.config(menu=menubar)
root.mainloop()
